server:
  port: 10086   #eureka服务的端口号
spring:
  application:
    name: leyoushop-registry
eureka:
  client:
    register-with-eureka: false   #不把自己注册到eureka中，
    fetch-registry: false       #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:10086/eureka   #注册中心服务的地址
  server:
    enable-self-preservation: false   #关闭自我保护模式
    eviction-interval-timer-in-ms: 10000    #定期清理无效链接